name: Venmo Pay
author: Austen Stone
description: Pay or Request money via Venmo
branding:
  icon: "dollar-sign"
  color: "blue"

inputs:
  phone_email_or_username:
    description: The phone, email, or username to login with
    required: true
  password:
    description: The password to login with
    required: true
  recipients:
    description: A list of comma separated usernames to send or request money from.
    required: true
  amount:
    description: The amount to send or request. Negative(-) amounts are requests, positive(+) are payments.
    required: true
  note:
    description: The note to send with the transaction
    required: true
  audience:
    description: The audience to send the transaction to. Either "public" or "private"
    required: true
  otp:
    description: The one time password sent to you over text.
    required: false
  otp_secret:
    description: Secret code output from login attempt if 2FA is required.
    required: false

outputs:
  otp_secret:
    description: Secret code output if 2FA is required.

runs:
  using: "node16"
  main: "dist/index.js"
