name: Rent OTP

on:
  workflow_dispatch:
    inputs:
      otp:
        description: 'Venmo OTP received by text.'
        required: true

jobs:
  run:
    name: Request Rent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get persistent OTP value
        id: otp
        uses: aaimio/get-persistent-value@v1.1.2
        with:
          key: otp_secret
          access_token: ${{ secrets.PERSISTENT_VALUE_ACCESS_TOKEN }}
      - uses: ./
        with:
          phone_email_or_username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          recipients: ${{ secrets.RECIPIENTS }}
          amount: -1.00
          note: Rent
          audience: Public
          otp: ${{ inputs.otp }}
          otp_secret: ${{ steps.otp.outputs.value }}
