name: Rent OTP

on:
  workflow_dispatch:
    inputs:
      otp:
        description: 'Venmo OTP received by text.'
        required: true

jobs:
  run:
    name: Request Rent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          phone_email_or_username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          recipients: Goosetoe,matthew-horwitz92
          amount: -1.00
          note: Rent
          audience: Public
          otp: ${{ inputs.otp }}
