name: Rent

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  run:
    name: Request Rent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: venmo-pay
        with:
          phone_email_or_username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          recipients: Goosetoe,matthew-horwitz92
          amount: -1.00
          note: Rent
          audience: Public
      - name: Persistent OTP secret
        uses: aaimio/set-persistent-value@v1.1.2
        with:
          key: otp_secret
          value: ${{ steps.venmo-pay.outputs.otp_secret }}
          access_token: ${{ secrets.PERSISTENT_VALUE_ACCESS_TOKEN }}